
spring:
  application:
    name: food-service

  datasource:
    url: jdbc:mysql://localhost:3306/substring_microservice
    username: root
    password: "{cipher}6ac20fbff9713140106dab2c17ce5fa25a205e879e1d205b112300684de0a22d"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Eureka Configurations

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

