
info.app.name=Restaurant Service
info.app.description=This is Restaurant Service. Ready to serve User!
info.app.version=1.0 Under Production

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurantdb
spring.datasource.username=postgres
spring.datasource.password=root

#Hibernate Properties

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
